version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=painel.lucasjanczak.com.br;Database=cotemig;User=mysql;Password=855be35b9fab607d8b93;
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
    command: ["./start.sh"]

  db:
    image: mysql:5.8
    environment:
      MYSQL_ROOT_PASSWORD: 855be35b9fab607d8b93
      MYSQL_DATABASE: cotemig
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
