name: Deploy on Master Commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer GET na URL de deploy
        run: curl -X GET http://89.116.73.154:3000/api/deploy/58e3e509692cd531285376738f092d4c62676baefec3cb94
